#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", or "lc")?
carpentry: "bw"

# Overall title for pages.
title: "Blue Waters: New User Training"

# Contact.  This *must* include the protocol:
# "mailto:" for emails .
# "http/https://" for URL addresses
email: "mailto:bw-eot@ncsa.illinois.edu"

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "lesson"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
# repository: maxim-belkin/bw-new-user-training
repository: <USERNAME>/<PROJECT>

# Sites.
bwportal: "https://bluewaters.ncsa.illinois.edu"
ncsaportal: "http://ncsa.illinois.edu"
otpportal: "http://otp.ncsa.illinois.edu"
swcstyles: "https://github.com/swcarpentry/styles.git"
bwhelpemail: "mailto:help+bw@ncsa.illinois.edu"

# Surveys.
# pre_survey: "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id="
# post_survey: "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id="
# training_post_survey: "https://www.surveymonkey.com/r/post-instructor-training"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am).
start_time: 0

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: ..
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn on built-in syntax highlighting.
highlighter: rouge
